<?php

namespace App\Services;

class HtaccessTemplateService
{
    public function forProjectType(string $projectType): string
    {
        $projectType = trim($projectType);
        if ($projectType === '') {
            $projectType = 'custom';
        }

        if ($projectType === 'laravel') {
            $lines = [
                '<IfModule mod_rewrite.c>',
                '    Options +SymLinksIfOwnerMatch -Indexes',
                '    RewriteEngine On',
                '',
                '    # Block direct access to sensitive files and directories outside',
                '    # /public/. They exist on disk, so without this rule the',
                '    # RewriteCond ... !-f check below would skip the rewrite and Apache',
                '    # would serve them as-is (.env, .git internals) with no',
                '    # authentication at all. None of these have a legitimate',
                '    # counterpart under /public/, so they\'re always blocked.',
                '    RewriteRule ^(\\.env(\\..*)?|\\.git(/.*)?|\\.htaccess|bootstrap(/.*)?|config(/.*)?|database(/.*)?|resources(/.*)?|routes(/.*)?|tests(/.*)?|node_modules(/.*)?|composer\\.(json|lock)|package(-lock)?\\.json|yarn\\.lock|pnpm-lock\\.yaml|artisan)$ - [F,L]',
                '',
                '    # storage/ and vendor/ also back legitimate public-facing paths:',
                '    # the storage:link symlink (public/storage) and vendor:publish',
                '    # assets (public/vendor/...), both requested as /storage/... or',
                '    # /vendor/... and expected to fall through to the /public/',
                '    # rewrite below. Only block them when the request resolves to a',
                '    # real file/directory at this level — the actual storage/ and',
                '    # vendor/ folders, not an asset that only exists once rewritten',
                '    # into /public/.',
                '    RewriteCond %{REQUEST_FILENAME} -f [OR]',
                '    RewriteCond %{REQUEST_FILENAME} -d',
                '    RewriteRule ^(storage(/.*)?|vendor(/.*)?)$ - [F,L]',
                '',
                '    RewriteCond %{REQUEST_URI} !^/public/',
                '',
                '    RewriteCond %{REQUEST_FILENAME} !-d',
                '    RewriteCond %{REQUEST_FILENAME} !-f',
                '',
                '    RewriteRule ^(.*)$ /public/$1',
                '    #RewriteRule ^ index.php [L]',
                '    RewriteRule ^(/)?$ public/index.php [L]',
                '</IfModule>',
            ];

            return implode("\n", $lines)."\n";
        }

        $lines = [
            '# Generated by Git Web Manager',
            '<IfModule mod_autoindex.c>',
            '    Options -Indexes',
            '</IfModule>',
            '',
            '<FilesMatch "(^\\.|\\.env|\\.git|composer\\.(json|lock)|package(-lock)?\\.json|yarn\\.lock|pnpm-lock\\.yaml)">',
            '    Require all denied',
            '</FilesMatch>',
            '',
            '<IfModule mod_rewrite.c>',
            '    RewriteEngine On',
            '',
            '    # <FilesMatch> above only matches the requested file\'s basename, so',
            '    # it never blocks sensitive directories (storage/, vendor/, .git/,',
            '    # node_modules/) whose contents have ordinary-looking filenames.',
            '    # Block those paths explicitly.',
            '    RewriteRule ^(\\.git(/.*)?|storage(/.*)?|vendor(/.*)?|node_modules(/.*)?)$ - [F,L]',
            '</IfModule>',
        ];

        if ($projectType === 'static') {
            $lines[] = '';
            $lines[] = '<IfModule mod_rewrite.c>';
            $lines[] = '    RewriteEngine On';
            $lines[] = '    RewriteCond %{REQUEST_FILENAME} !-f';
            $lines[] = '    RewriteCond %{REQUEST_FILENAME} !-d';
            $lines[] = '    RewriteRule ^ index.html [L]';
            $lines[] = '</IfModule>';
        }

        return implode("\n", $lines)."\n";
    }
}
