<?php

namespace App\Services;

class HtaccessTemplateService
{
    public function forProjectType(string $projectType): string
    {
        $projectType = trim($projectType);
        if ($projectType === '') {
            $projectType = 'custom';
        }

        if ($projectType === 'laravel') {
            $lines = [
                '<IfModule mod_rewrite.c>',
                '    Options +SymLinksIfOwnerMatch',
                '    RewriteEngine On',
                '',
                '    RewriteCond %{REQUEST_URI} !^/public/',
                '',
                '    RewriteCond %{REQUEST_FILENAME} !-d',
                '    RewriteCond %{REQUEST_FILENAME} !-f',
                '',
                '    RewriteRule ^(.*)$ /public/$1',
                '    #RewriteRule ^ index.php [L]',
                '    RewriteRule ^(/)?$ public/index.php [L]',
                '</IfModule>',
            ];

            return implode("\n", $lines)."\n";
        }

        $lines = [
            '# Generated by Git Web Manager',
            '<IfModule mod_autoindex.c>',
            '    Options -Indexes',
            '</IfModule>',
            '',
            '<FilesMatch "(^\\.|\\.env|\\.git|composer\\.(json|lock)|package(-lock)?\\.json|yarn\\.lock|pnpm-lock\\.yaml)">',
            '    Require all denied',
            '</FilesMatch>',
        ];

        if ($projectType === 'static') {
            $lines[] = '';
            $lines[] = '<IfModule mod_rewrite.c>';
            $lines[] = '    RewriteEngine On';
            $lines[] = '    RewriteCond %{REQUEST_FILENAME} !-f';
            $lines[] = '    RewriteCond %{REQUEST_FILENAME} !-d';
            $lines[] = '    RewriteRule ^ index.html [L]';
            $lines[] = '</IfModule>';
        }

        return implode("\n", $lines)."\n";
    }
}
